package com.mycompany.traductorjava;

import java.util.HashMap;
import java.util.Scanner;

public class TraductorJava {

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        HashMap<Integer, String> numeros = new HashMap<>();
        numeros.put( 0, "cero");
        numeros.put( 1, "uno");
        numeros.put( 2, "dos");
        numeros.put( 3, "tres");
        numeros.put( 4, "cuatro");
        numeros.put( 5, "cinco");
        numeros.put( 6, "seis");
        numeros.put( 7, "siete");
        numeros.put( 8, "ocho");
        numeros.put( 9, "nueve");
        numeros.put( 10, "diez");
        numeros.put( 11, "once");
        numeros.put( 12, "doce");
        numeros.put( 13, "trece");
        numeros.put( 14, "catorce");
        numeros.put( 15, "quince");
        numeros.put( 16, "dieciséis");
        numeros.put( 17, "diecisiete");
        numeros.put( 18, "dieciocho");
        numeros.put( 19, "diecinueve");
        numeros.put( 20, "veinte");
        numeros.put( 21, "veintiuno");
        numeros.put( 22, "veintidós");
        numeros.put( 23, "veintitrés");
        numeros.put( 24, "veinticuatro");
        numeros.put( 25, "veinticinco");
        numeros.put( 26, "veintiséis");
        numeros.put( 27, "veintisiete");
        numeros.put( 28, "veintiocho");
        numeros.put( 29, "veintinueve");
        numeros.put( 30, "treinta");
        numeros.put( 31, "treinta y uno");
        numeros.put( 32, "treinta y dos");
        numeros.put( 33, "treinta y tres");
        numeros.put( 34, "treinta y cuatro");
        numeros.put( 35, "treinta y cinco");
        numeros.put( 36, "treinta y seis");
        numeros.put( 37, "treinta y siete");
        numeros.put( 38, "treinta y ocho");
        numeros.put( 39, "treinta y nueve");
        numeros.put( 40, "cuarenta");
        numeros.put( 41, "cuarenta y uno");
        numeros.put( 42, "cuarenta y dos");
        numeros.put( 43, "cuarenta y tres");
        numeros.put( 44, "cuarenta y cuatro");
        numeros.put( 45, "cuarenta y cinco");
        numeros.put( 46, "cuarenta y seis");
        numeros.put( 47, "cuarenta y siete");
        numeros.put( 48, "cuarenta y ocho");
        numeros.put( 49, "cuarenta y nueve");
        numeros.put( 50, "cincuenta");
        numeros.put( 51, "cincuenta y uno");
        numeros.put( 52, "cincuenta y dos");
        numeros.put( 53, "cincuenta y tres");
        numeros.put( 54, "cincuenta y cuatro");
        numeros.put( 55, "cincuenta y cinco");
        numeros.put( 56, "cincuenta y seis");
        numeros.put( 57, "cincuenta y siete");
        numeros.put( 58, "cincuenta y ocho");
        numeros.put( 59, "cincuenta y nueve");
        numeros.put( 60, "sesenta");
        numeros.put( 61, "sesenta y uno");
        numeros.put( 62, "sesenta y dos");
        numeros.put( 63, "sesenta y tres");
        numeros.put( 64, "sesenta y cuatro");
        numeros.put( 65, "sesenta y cinco");
        numeros.put( 66, "sesenta y seis");
        numeros.put( 67, "sesenta y siete");
        numeros.put( 68, "sesenta y ocho");
        numeros.put( 69, "sesenta y nueve");
        numeros.put( 70, "setenta");
        numeros.put( 71, "setenta y uno");
        numeros.put( 72, "setenta y dos");
        numeros.put( 73, "setenta y tres");
        numeros.put( 74, "setenta y cuatro");
        numeros.put( 75, "setenta y cinco");
        numeros.put( 76, "setenta y seis");
        numeros.put( 77, "setenta y siete");
        numeros.put( 78, "setenta y ocho");
        numeros.put( 79, "setenta y nueve");
        numeros.put( 80, "ochenta");
        numeros.put( 81, "ochenta y uno");
        numeros.put( 82, "ochenta y dos");
        numeros.put( 83, "ochenta y tres");
        numeros.put( 84, "ochenta y cuatro");
        numeros.put( 85, "ochenta y cinco");
        numeros.put( 86, "ochenta y seis");
        numeros.put( 87, "ochenta y siete");
        numeros.put( 88, "ochenta y ocho");
        numeros.put( 89, "ochenta y nueve");
        numeros.put( 90, "noventa");
        numeros.put( 91, "noventa y uno");
        numeros.put( 92, "noventa y dos");
        numeros.put( 93, "noventa y tres");
        numeros.put( 94, "noventa y cuatro");
        numeros.put( 95, "noventa y cinco");
        numeros.put( 96, "noventa y seis");
        numeros.put( 97, "noventa y siete");
        numeros.put( 98, "noventa y ocho");
        numeros.put( 99, "noventa y nueve");
        numeros.put( 100, "cien");
        HashMap<Integer, String> numbers = new HashMap<>();
         numbers.put( 0, "zero");
        numbers.put( 1, "one");
        numbers.put( 2, "two");
        numbers.put( 3, "three");
        numbers.put( 4, "four");
        numbers.put( 5, "five");
        numbers.put( 6, "six");
        numbers.put( 7, "seven");
        numbers.put( 8, "eight");
        numbers.put( 9, "nine");
        numbers.put( 10, "ten");
        numbers.put( 11, "eleven");
        numbers.put( 12, "twelve");
        numbers.put( 13, "thirteen");
        numbers.put( 14, "fourteen");
        numbers.put( 15, "fifteen");
        numbers.put( 16, "sixteen");
        numbers.put( 17, "seventeen");
        numbers.put( 18, "eighteen");
        numbers.put( 19, "nineteen");
        numbers.put( 20, "twenty");
        numbers.put( 21, "twenty-one");
        numbers.put( 22, "twenty-two");
        numbers.put( 23, "twenty-three");
        numbers.put( 24, "twenty-four");
        numbers.put( 25, "twenty-five");
        numbers.put( 26, "twenty-six");
        numbers.put( 27, "twenty-seven");
        numbers.put( 28, "twenty-eight");
        numbers.put( 29, "twenty-nine");
        numbers.put( 30, "thirty");
        numbers.put( 31, "thirty-one");
        numbers.put( 32, "thirty-two");
        numbers.put( 33, "thirty-three");
        numbers.put( 34, "thirty-four");
        numbers.put( 35, "thirty-five");
        numbers.put( 36, "thirty-six");
        numbers.put( 37, "thirty-seven");
        numbers.put( 38, "thirty-eight");
        numbers.put( 39, "thirty-nine");
        numbers.put( 40, "forty");
        numbers.put( 41, "forty-one");
        numbers.put( 42, "forty-two");
        numbers.put( 43, "forty-three");
        numbers.put( 44, "forty-four");
        numbers.put( 45, "forty-five");
        numbers.put( 46, "forty-six");
        numbers.put( 47, "forty-seven");
        numbers.put( 48, "forty-eight");
        numbers.put( 49, "forty-nine");
        numbers.put( 50, "fifty");
        numbers.put( 51, "fifty-one");
        numbers.put( 52, "fifty-two");
        numbers.put( 53, "fifty-three");
        numbers.put( 54, "fifty-four");
        numbers.put( 55, "fifty-five");
        numbers.put( 56, "fifty-six");
        numbers.put( 57, "fifty-seven");
        numbers.put( 58, "fifty-eight");
        numbers.put( 59, "fifty-nine");
        numbers.put( 60, "sixty");
        numbers.put( 61, "sixty-one");
        numbers.put( 62, "sixty-two");
        numbers.put( 63, "sixty-three");
        numbers.put( 64, "sixty-four");
        numbers.put( 65, "sixty-five");
        numbers.put( 66, "sixty-six");
        numbers.put( 67, "sixty-seven");
        numbers.put( 68, "sixty-eight");
        numbers.put( 69, "sixty-nine");
        numbers.put( 70, "seventy");
        numbers.put( 71, "seventy-one");
        numbers.put( 72, "seventy-two");
        numbers.put( 73, "seventy-three");
        numbers.put( 74, "seventy-four");
        numbers.put( 75, "seventy-five");
        numbers.put( 76, "seventy-six");
        numbers.put( 77, "seventy-seven");
        numbers.put( 78, "seventy-eight");
        numbers.put( 79, "seventy-nine");
        numbers.put( 80, "eighty");
        numbers.put( 81, "eighty-one");
        numbers.put( 82, "eighty-two");
        numbers.put( 83, "eighty-three");
        numbers.put( 84, "eighty-four");
        numbers.put( 85, "eighty-five");
        numbers.put( 86, "eighty-six");
        numbers.put( 87, "eighty-seven");
        numbers.put( 88, "eighty-eight");
        numbers.put( 89, "eighty-nine");
        numbers.put( 90, "ninety");
        numbers.put( 91, "ninety-one");
        numbers.put( 92, "ninety-two");
        numbers.put( 93, "ninety-three");
        numbers.put( 94, "ninety-four");
        numbers.put( 95, "ninety-five");
        numbers.put( 96, "ninety-six");
        numbers.put( 97, "ninety-seven");
        numbers.put( 98, "ninety-eight");
        numbers.put( 99, "ninety-nine");
        numbers.put( 100, "one hundred");
        System.out.println("Introduce el primer numero del uno al cien (1-100): ");
        int numero1 = scan.nextInt();
        System.out.println("Introduce el segundo numero del uno al cien (1-100): ");
        int numero2 = scan.nextInt();
        int suma = numero1+numero2;
        String español = "La suma del numero "+numeros.get(numero1)+" y el numero "+numeros.get(numero2)+" es: "+numeros.get(suma);
        String english = "The plus of number "+numbers.get(numero1)+" and number "+numbers.get(numero2)+" is: "+numbers.get(suma);
        System.out.println(español);
        System.out.println(english);
    }
}
